### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by IamFonky** [aknuds1/html-to-react#121]
Is there any type definitions that can be used for this awesome module?

**Comment by aknuds1** [comment]
I'm not aware of any, sorry. If you don't find any, maybe you could provide a PR?

**Comment by alexaivars** [comment]
> Is there any type definitions that can be used for this awesome module?

@IamFonky Im not experienced enough with TS but if your up to it you can create a pr in the DefinitelyTyped  project https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by IamFonky** [comment]
I will do it as soon as I have the time then!

**Comment by alexaivars** [comment]
if its any help I found this https://github.com/antokara/spsa.church/blob/87d3b1367dee91d86ad0292aad4bcddea322ed23/types/html-to-react/index.d.ts that looks like a good starting point.

**Comment by justdvl** [comment]
Thank you @alexaivars , how do I use this in my NextJS app (I don't know where to put it, I tried putting it into new file in @types folder but got TS error
error TS1208: 'html-to-react.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
