### ISSUE TITLE
Boolean camelCase attributes are processed incorrectly

### ISSUE THREAD

**Issue by ArtemNizelnyk** [aknuds1/html-to-react#129]
[test.txt](https://github.com/aknuds1/html-to-react/files/6984763/test.txt)
Simple test.js code for reproduction.
Steps to reproduce:

Run command `node test.js`
**Actual Result:** input element doesn't have `readonly` attrib
**Expected Result:**  input element has `readonly` attrib

The problem is with the: Util.createElement function.
`key = camelCaseAttrMap[key.replace(/[-:]/, '')] || key;`

then

      `if (includes(key, booleanAttrs) && (value || '') === '') {
        value = key;
      }`
  camelCase attributes will be always ignored because :
  it compares camelCase **key** (readOnly) with lowercase collection **booleanAttrs**

**Comment by aknuds1** [comment]
Can you specify _which_ camel case HTML attributes are not handled correctly? If you look at the [reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete), `autoComplete` (from your test.txt file) is incorrect HTML, it should be `autocomplete`.

Are you saying that `readonly` isn't handled correctly in your example? `readonly` should be handled by the code, since it's already lowercase.

**Comment by ArtemNizelnyk** [comment]
All of the attributes which are CamelCased:
[Here we CamelCase attribute](https://github.com/aknuds1/html-to-react/blob/ed27c484be9e059272ec71c7e42d75f24c2afca2/lib/utils.js#L70)

This will result in always "False" here:
[](https://github.com/aknuds1/html-to-react/blob/ed27c484be9e059272ec71c7e42d75f24c2afca2/lib/utils.js#L79)
for `includes(key, booleanAttrs)`
