### ISSUE TITLE
[Request] ES6 Example

### ISSUE THREAD

**Issue by khorolets** [aknuds1/html-to-react#16]
Hi everyone!

First of all thanks for a great project. I wonder if anybody has an example of usage with ES6?

**Comment by aknuds1** [comment]
What would you like to learn about using html-to-react in ES6? The API is pretty basic, so translating to ES6 should be straightforward presumably.

**Comment by khorolets** [comment]
@aknuds1 Hi! Thanks for your answer and I'm sorry for the delay.

I'm not quite good in nowadays frontend development, so I can't find out how to make this import in ES6.

```javascript
var HtmlToReactParser = require('html-to-react').Parser;
```

Also, can you give, at least, a direction to understand how to use it with JSX:

```javascript
var htmlToReactParser = new HtmlToReactParser();
var reactComponent = htmlToReactParser.parse(htmlInput);
var reactHtml = React.renderToStaticMarkup(reactComponent);

assert.equal(reactHtml, htmlInput); // true
```

I'm sorry if this question is too newbie (or even stupid) and I'll understand if you'd not answer that :)

Thanks.

**Comment by aknuds1** [comment]
`require` is not part of *standard* JavaScript, you will need to either be in a Node environment or be using a framework providing it in the browser, such as [Webpack](http://webpack.github.io/) or [Browserify](http://browserify.org). I haven't tried the ES6 import system, but I gather the [rollup](http://rollupjs.org/) tool allows you to use this syntax, so I would try combining that with html-to-react.

I don't know JSX so well either, since I haven't used it in ages, but basically, `htmlToReactParser.parse(htmlInput)` gives you a [React element](https://facebook.github.io/react/blog/2014/10/14/introducing-react-elements.html), which you can embed in JSX as much as you like.

**Comment by tomershvueliebsco** [comment]
@khorolets did you ever get some syntax working for ES6 imports?

**Comment by khorolets** [comment]
@tomershvueliebsco This package doesn't solve my issue, I don't use it. And no, I hadn't succeed in ES6 imports here. Cheers!
