### ISSUE TITLE
Self-closing sibling elements not in `voidElementTags` get parsed wrong

### ISSUE THREAD

**Issue by claudiorodriguez** [aknuds1/html-to-react#39]
Hello there! I don't know if I'm doing something wrong, but when I try to parse this string:

`<div><test /><test /><test /></div>`

with custom `processingInstructions` that do a `createElement`, I don't receive three siblings, I receive three nested children - the parser seems to think this is what's happening:
`<div><test><test><test></test></test></test></div>`

Same with any self-closing tag not in `voidElementTags`

In case it's any use, the package `html2json` seems to parse it into the correct json tree structure and converts it back into html adding closing tags to non-self-closing tags (so sanitising the html input for html-to-react with `json2html(html2json(html))` is a quick workaround)

Also related, if you try to parse `<textarea>some value</textarea>` it will swallow the value because children of `voidElementTags` get ignored

**Comment by aknuds1** [comment]
Your best bet is to write a PR, which at the very least adds a test for your failing scenario. Preferably it should also fix the bug in question (if it is indeed a bug).

**Comment by ZonRobin** [comment]
This is because this parser is by the default set to parsing HTML. <test /> is not a valid self-closing HTML tag, so when it's parsed by DOMParser it tries to fix it by closing it.
To resolve this issue, all you have to do is just put` {xmlMode: true}` setting in the constructor of `HtmlToReactParser()`. It then parses the input as XML and behaves as you'd expect.

**Comment by aknuds1** [comment]
Seems as if this is indeed related to parsing in HTML mode rather than XML.
